name: 'twilio' 
version: '0.1.1'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  twilio:
    account_history: "{{ ref('stg_twilio__account_history' )}}"
    address: "{{ ref('stg_twilio__address' )}}"
    call: "{{ ref('stg_twilio__call' )}}"
    incoming_phone_number: "{{ ref('stg_twilio__incoming_phone_number' )}}"
    message: "{{ ref('stg_twilio__message' )}}"
    messaging_service: "{{ ref('stg_twilio__messaging_service' )}}"
    outgoing_caller_id: "{{ ref('stg_twilio__outgoing_caller_id' )}}"
    usage_record: "{{ ref('stg_twilio__usage_record' )}}"

models:
  twilio:
    +materialized: table
    +schema: twilio
