name: 'twilio_integration_tests'
version: '1.4.0'
config-version: 2
profile: 'integration_tests'

vars:
  twilio_schema: twilio_integration_tests
  twilio:
    twilio_account_history_identifier: "twilio_account_history_data"
    twilio_address_identifier: "twilio_address_data"
    twilio_incoming_phone_number_identifier: "twilio_incoming_phone_number_data"
    twilio_messaging_service_identifier: "twilio_messaging_service_data"
    twilio_outgoing_caller_id_identifier: "twilio_outgoing_caller_id_data"
    twilio_usage_record_identifier: "twilio_usage_record_data"
    twilio_call_identifier: "twilio_call_data"
    twilio_message_identifier: "twilio_message_data"
  

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  +persist_docs:
    relation: true
    columns: "{{ false if target.type in ('databricks') else true }}"
  +schema: "twilio_{{ var('directed_schema','dev') }}"

seeds:
  +docs:
    show: False
  +quote_columns: "{{ target.type in ('redshift','postgres') or var('fivetran_using_source_casing', false) }}"
  twilio_integration_tests:
    twilio_call_data:
      +enabled: "{{ target.type != 'snowflake' or var('fivetran_using_source_casing', false) }}"
      +column_types:
        to: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        from: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        forwarded_from: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
    twilio_message_data:
      +enabled: "{{ target.type != 'snowflake' or var('fivetran_using_source_casing', false) }}"
      +column_types:
        to: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        from: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
    twilio_message_data_snowflake:
      +enabled: "{{ target.type == 'snowflake' and not var('fivetran_using_source_casing', false) }}"
      +alias: twilio_message_data
    twilio_call_data_snowflake:
      +enabled: "{{ target.type == 'snowflake' and not var('fivetran_using_source_casing', false) }}"
      +alias: twilio_call_data
    twilio_address_data:
      +column_types:
        friendly_name: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
    twilio_incoming_phone_number_data:
      +column_types:
        phone_number: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        friendly_name: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
    twilio_messaging_service_data:
      +column_types:
        friendly_name: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
    twilio_outgoing_caller_id_data:
      +column_types:
        phone_number: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        friendly_name: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"

flags:
  send_anonymous_usage_stats: False
  use_colors: True